name:       csv-ql
version:    0.1.0.0
github:     "Vandalord12/PC-Coursework"
license:    BSD-3-Clause
author:     "Abdullah-Muhammed-Manu"
copyright:  "Southampton Univerity 2025"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: CSV Query Language.

dependencies:
- base >= 4.7 && < 5
- array

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
   cql: # program-run:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-ql

tests:
  example-name-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-ql
